version: "3.3"
services:
  audi-mysql:
    image: mysql:5.7
    container_name: audi-mysql1
    restart: always
    ports:
      - "3311:3306"
    volumes:
      - ./mysql-database:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
